[2020-06-10 22:03:27.158] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:03:27.247] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:03:27.381] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:03:38.769] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:03:38.770] [ERROR] console - TSError: ‚®Ø Unable to compile TypeScript:
[96mgame/network/default_slist.ts[0m:[93m43[0m:[93m25[0m - [91merror[0m[90m TS7006: [0mParameter 'lsocket' implicitly has an 'any' type.

[7m43[0m     ['connect_error']: (lsocket, data) => {
[7m  [0m [91m                        ~~~~~~~[0m
[96mgame/network/default_slist.ts[0m:[93m43[0m:[93m34[0m - [91merror[0m[90m TS7006: [0mParameter 'data' implicitly has an 'any' type.

[7m43[0m     ['connect_error']: (lsocket, data) => {
[7m  [0m [91m                                 ~~~~[0m

    at createTSError (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:434:12)
    at reportTSError (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:438:19)
    at getOutput (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:578:36)
    at Object.compile (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:775:32)
    at Module._compile (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:858:43)
    at internal/modules/cjs/loader.js:1196:10
    at Object..ts (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
[2020-06-10 22:03:56.319] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:03:56.320] [ERROR] console - TSError: ‚®Ø Unable to compile TypeScript:
[96mgame/network/default_slist.ts[0m:[93m43[0m:[93m25[0m - [91merror[0m[90m TS7006: [0mParameter 'lsocket' implicitly has an 'any' type.

[7m43[0m     ['connect_error']: (lsocket, data) => {
[7m  [0m [91m                        ~~~~~~~[0m
[96mgame/network/default_slist.ts[0m:[93m43[0m:[93m34[0m - [91merror[0m[90m TS7006: [0mParameter 'data' implicitly has an 'any' type.

[7m43[0m     ['connect_error']: (lsocket, data) => {
[7m  [0m [91m                                 ~~~~[0m

    at createTSError (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:434:12)
    at reportTSError (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:438:19)
    at getOutput (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:578:36)
    at Object.compile (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:775:32)
    at Module._compile (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:858:43)
    at internal/modules/cjs/loader.js:1196:10
    at Object..ts (/Users/brightli/Documents/work/server/dhxy/node_modules/_ts-node@8.10.2@ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
[2020-06-10 22:04:48.708] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:04:48.794] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:04:48.906] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:04:53.122] [INFO] console - [ÊµãËØïÂå∫]ÂÆåÊàêÊ≥®ÂÜå
[2020-06-10 22:04:53.132] [INFO] console - [ÁΩëÂÖ≥Êúç]ÂÆåÊàêÊ≥®ÂÜå
[2020-06-10 22:04:53.230] [INFO] console - SQL: select text, type from qy_notice where serverid = 1000 or serverid = 0 order by time desc limit 30;
[2020-06-10 22:04:53.244] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.244] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.258] [INFO] console - SQL: SELECT MAX(EquipID) AS equipid FROM qy_equip_1000;
[2020-06-10 22:04:53.259] [INFO] console - SQL: SELECT * FROM qy_bang WHERE state = 1 and serverid = 1000;
[2020-06-10 22:04:53.261] [INFO] console - SQL: SELECT MAX(bangid) AS bangId FROM qy_bang WHERE serverid = 1000;
[2020-06-10 22:04:53.262] [INFO] console - SQL: select * from shop_goods
[2020-06-10 22:04:53.263] [INFO] console - SQL: SELECT MAX(petid) AS petid FROM qy_pet_1000;
[2020-06-10 22:04:53.264] [INFO] console - SQL: SELECT roleid, sum(realmoney) AS rmb FROM charge_record WHERE status = 1 GROUP BY roleid;
[2020-06-10 22:04:53.266] [INFO] console - SQL: SELECT * FROM qy_role
[2020-06-10 22:04:53.267] [INFO] console - SQL: select * from qy_relation where status = 0
[2020-06-10 22:04:53.268] [INFO] console - SQL: select max(relationId) as relationId from qy_relation;
[2020-06-10 22:04:53.269] [INFO] console - SQL: SELECT MAX(EquipID) AS equipid FROM qy_equip_1000;
[2020-06-10 22:04:53.270] [INFO] console - SQL: SELECT MAX(bangid) AS bangId FROM qy_bang WHERE serverid = 1000;
[2020-06-10 22:04:53.270] [INFO] console - SQL: SELECT MAX(petid) AS petid FROM qy_pet_1000;
[2020-06-10 22:04:53.271] [INFO] console - SQL: select max(relationId) as relationId from qy_relation;
[2020-06-10 22:04:53.276] [INFO] console - SQL: select * from qy_agent
[2020-06-10 22:04:53.277] [INFO] console - SQL: SELECT frozenip FROM ip_frozen;
[2020-06-10 22:04:53.278] [INFO] console - SQL: SELECT mac FROM mac_frozen;
[2020-06-10 22:04:53.278] [INFO] console - SQL: SELECT * FROM qy_account WHERE account = 'test05';
[2020-06-10 22:04:53.278] [INFO] console - SQL: SELECT * FROM qy_account WHERE account = 'test05';
[2020-06-10 22:04:53.279] [INFO] console - SQL: SELECT * FROM qy_account WHERE account = 'test05';
[2020-06-10 22:04:53.282] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.283] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.298] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.299] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.304] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.304] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.317] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.317] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.324] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.325] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.333] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.334] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.339] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.339] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.345] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.346] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.350] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.351] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.355] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.355] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:04:53.358] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.359] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:04:53.395] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.396] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:04:53.403] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.403] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:04:53.406] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.406] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:04:53.409] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.409] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:04:53.411] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.412] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:04:53.414] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.414] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:04:53.416] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.417] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:04:53.423] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:04:53.423] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:05:38.608] [INFO] console - SQL: SELECT MAX(EquipID) AS equipid FROM qy_equip_1000;
[2020-06-10 22:05:38.613] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:05:38.614] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:05:38.616] [INFO] console - SQL: SELECT MAX(bangid) AS bangId FROM qy_bang WHERE serverid = 1000;
[2020-06-10 22:05:38.617] [INFO] console - SQL: SELECT MAX(petid) AS petid FROM qy_pet_1000;
[2020-06-10 22:05:38.621] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:05:38.621] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:05:38.625] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:05:38.626] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:05:38.688] [INFO] console - SQL: select max(relationId) as relationId from qy_relation;
[2020-06-10 22:05:38.692] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:05:38.693] [ERROR] console - Error: connect ENOENT 129.211.4.181
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:10:35.777] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:10:41.456] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:10:41.574] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:11:23.183] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:11:27.217] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:11:27.320] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:18:27.036] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:18:27.128] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:18:27.272] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:37:51.034] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:37:51.120] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:37:51.233] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:40:45.043] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:40:45.133] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:40:45.252] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:41:55.084] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:41:55.166] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:41:55.279] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:44:24.456] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:44:24.544] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:44:24.672] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:54:13.748] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:54:13.835] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:54:28.992] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:54:34.183] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:54:34.251] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:54:34.342] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:54:53.229] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:54:53.298] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:54:53.389] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:56:02.816] [INFO] console - Á≥ªÁªüÈÖçÁΩÆË°®Âä†ËΩΩÂÆåÊØï
[2020-06-10 22:56:08.270] [INFO] console - Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊØï
[2020-06-10 22:56:08.366] [INFO] console - Êï∞ÊçÆÂ∫ìÊ®°ÂùóÂêØÂä®ÂÆåÊØïÔºåÊ≠£Âú®ÁõëÂê¨Êú¨Âú∞:8806
[2020-06-10 22:56:51.631] [INFO] console - [ÊµãËØïÂå∫]ÂÆåÊàêÊ≥®ÂÜå
[2020-06-10 22:57:11.974] [INFO] console - [ÁΩëÂÖ≥Êúç]ÂÆåÊàêÊ≥®ÂÜå
[2020-06-10 22:57:15.301] [INFO] console - SQL: select * from qy_agent
[2020-06-10 22:57:18.773] [INFO] console - SQL: SELECT frozenip FROM ip_frozen;
[2020-06-10 22:57:18.774] [INFO] console - SQL: SELECT mac FROM mac_frozen;
[2020-06-10 22:57:18.775] [INFO] console - SQL: select * from qy_agent
[2020-06-10 22:57:18.776] [INFO] console - SQL: SELECT frozenip FROM ip_frozen;
[2020-06-10 22:57:18.777] [INFO] console - SQL: SELECT mac FROM mac_frozen;
[2020-06-10 22:57:22.501] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:25.715] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:25.719] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:25.720] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:25.729] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:25.729] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:25.733] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:25.733] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:25.736] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:25.737] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:25.744] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:25.744] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.500] [INFO] console - [ÊµãËØïÂå∫]ÂÆåÊàêÊ≥®ÂÜå
[2020-06-10 22:57:55.604] [INFO] console - SQL: select text, type from qy_notice where serverid = 1000 or serverid = 0 order by time desc limit 30;
[2020-06-10 22:57:55.614] [INFO] console - SQL: SELECT MAX(EquipID) AS equipid FROM qy_equip_1000;
[2020-06-10 22:57:55.615] [INFO] console - SQL: SELECT * FROM qy_bang WHERE state = 1 and serverid = 1000;
[2020-06-10 22:57:55.616] [INFO] console - SQL: SELECT MAX(bangid) AS bangId FROM qy_bang WHERE serverid = 1000;
[2020-06-10 22:57:55.617] [INFO] console - SQL: select * from shop_goods
[2020-06-10 22:57:55.618] [INFO] console - SQL: SELECT MAX(petid) AS petid FROM qy_pet_1000;
[2020-06-10 22:57:55.619] [INFO] console - SQL: SELECT roleid, sum(realmoney) AS rmb FROM charge_record WHERE status = 1 GROUP BY roleid;
[2020-06-10 22:57:55.620] [INFO] console - SQL: SELECT * FROM qy_role
[2020-06-10 22:57:55.621] [INFO] console - SQL: select * from qy_relation where status = 0
[2020-06-10 22:57:55.622] [INFO] console - SQL: select max(relationId) as relationId from qy_relation;
[2020-06-10 22:57:55.623] [INFO] console - SQL: SELECT MAX(EquipID) AS equipid FROM qy_equip_1000;
[2020-06-10 22:57:55.623] [INFO] console - SQL: SELECT MAX(bangid) AS bangId FROM qy_bang WHERE serverid = 1000;
[2020-06-10 22:57:55.623] [INFO] console - SQL: SELECT MAX(petid) AS petid FROM qy_pet_1000;
[2020-06-10 22:57:55.624] [INFO] console - SQL: select max(relationId) as relationId from qy_relation;
[2020-06-10 22:57:55.637] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.638] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.650] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.650] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.657] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.658] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.660] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.661] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.663] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.664] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.667] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.668] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.670] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.670] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.672] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.672] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.675] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.676] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.677] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.678] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:57:55.694] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.694] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:57:55.697] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.697] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:57:55.699] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.699] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:57:55.702] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:55.702] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.releaseConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:157:10)
    at Pool._removeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:258:8)
    at Handshake.onConnect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:57:14)
    at Handshake.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:468:16)
[2020-06-10 22:57:57.067] [INFO] console - SQL: SELECT * FROM qy_account WHERE account = 'test07';
[2020-06-10 22:57:57.100] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:57:57.101] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:58:10.206] [INFO] console - <receive data> disconnect ping timeout
[2020-06-10 22:58:29.209] [INFO] console - SQL: SELECT MAX(EquipID) AS equipid FROM qy_equip_1000;
[2020-06-10 22:58:29.212] [INFO] console - SQL: SELECT MAX(bangid) AS bangId FROM qy_bang WHERE serverid = 1000;
[2020-06-10 22:58:29.215] [INFO] console - SQL: SELECT MAX(petid) AS petid FROM qy_pet_1000;
[2020-06-10 22:58:29.259] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:58:29.260] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:58:29.263] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:58:29.263] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:58:29.271] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:58:29.271] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:58:29.320] [INFO] console - SQL: select max(relationId) as relationId from qy_relation;
[2020-06-10 22:58:29.363] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:58:29.364] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:59:29.215] [INFO] console - SQL: SELECT MAX(EquipID) AS equipid FROM qy_equip_1000;
[2020-06-10 22:59:29.218] [INFO] console - SQL: SELECT MAX(bangid) AS bangId FROM qy_bang WHERE serverid = 1000;
[2020-06-10 22:59:29.219] [INFO] console - SQL: SELECT MAX(petid) AS petid FROM qy_pet_1000;
[2020-06-10 22:59:29.249] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:59:29.251] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:59:29.254] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:59:29.255] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:59:29.257] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:59:29.257] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-06-10 22:59:29.325] [INFO] console - SQL: select max(relationId) as relationId from qy_relation;
[2020-06-10 22:59:29.355] [ERROR] console - An uncaught error occurred!
[2020-06-10 22:59:29.355] [ERROR] console - Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'xy_game'@'211.161.249.134' (using password: YES)
    at Handshake._packetToError (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
    --------------------
    at Protocol._enqueue (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/brightli/Documents/work/server/dhxy/node_modules/mysql/lib/Pool.js:48:16)
    at query (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:28:7)
    at fsql (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:81:2)
    at Socket.<anonymous> (/Users/brightli/Documents/work/server/dhxy/DBServ.ts:120:3)
    at Socket.emit (events.js:315:20)
    at /Users/brightli/Documents/work/server/dhxy/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
